### ISSUE TITLE
You will like a monorepo

### ISSUE THREAD

**Issue by szepeviktor** [decodelabs/veneer#10]
Please see https://github.com/symplify/monorepo-builder

Among others tooling ~~could~~ will be centralized.
It has many-many benefits.

(He is also called Tomas.)

**Comment by betterthanclay** [comment]
There are significant benefits and drawbacks to switching to a monorepo structure. I'm still weighing up whether it makes sense for these libraries as they are designed to work semi-independently and version number shouldn't necessarily be tied to other unrelated libraries just for the sake of having all the code in one place.

It would also make for awkward version numbers before v1 public release as the monorepo would have to take on the highest current minor version of any library in the set, + 1 (v0.19.0) to still work correctly.

Monorepos totally make sense when you are using all of the components in a framework environment where all parts get updated together, but it adds unnecessary developer overhead when independent packages have their version number bumped regularly even if they don't change, especially early on when lots of things change regularly across the whole set packages.
