### ISSUE TITLE
explode() is never empty

### ISSUE THREAD

**Issue by szepeviktor** [decodelabs/veneer#11]
https://github.com/decodelabs/veneer/blob/58ba9c3271e2b1e1d18cda83b5194eab79339a1c/src/Veneer/Binding.php#L211-L214

Exploding an empty string returns `[""]`.

Actually the nullable `$namespace` makes it complicated.
String operations are under viktor-sanctions 🙃

**Comment by szepeviktor** [comment]
The class source code could be an array of lines and at the end: `return implode("\n", $classLines);`

**Comment by betterthanclay** [comment]
Hi Viktor.

The string being exploded can't be empty (it's considered a class-string by PHPStan) - at the very least it will contain a root namespace class name, (eg \MyClass), it's usually namespaced though.

In all cases, the class name gets popped off the array (line 212) - the empty($parts) line then looks to see if there are any namespace components left to work with. There will never be a case where $parts == [''] without passing in invalid class strings which is non-sensical.


With regards to using implode() to build the class source, yes, it _could_ but there's very little benefit to doing that now as it's more likely to introduce errors. Don't fix what ain't broke!

**Comment by szepeviktor** [comment]
> The string being exploded can't be empty

Then the elseif branch will never run

https://github.com/decodelabs/veneer/blob/58ba9c3271e2b1e1d18cda83b5194eab79339a1c/src/Veneer/Binding.php#L222

**Comment by betterthanclay** [comment]
That's a different variable than the one being worked on by explode() - that variable exists to allow for calling code to pass a default mount point namespace for the Proxy class.

By line 214 the $parts array may or may not be empty depending on if $this->proxyClass is in a namespace.

It's a little fiddly as there are a few odd cases for namespaces, but this code does exactly what it needs to do.

**Comment by szepeviktor** [comment]
AFAIK

https://github.com/decodelabs/veneer/blob/58ba9c3271e2b1e1d18cda83b5194eab79339a1c/src/Veneer/Binding.php#L211-L214

this is always true.
I leave it 100% up to you.

**Comment by betterthanclay** [comment]
Not if there is no namespace in the proxyClass. Class strings are not prefixed with a backslash.

$this->proxyClass = 'MyRootClass';
$parts = explode('\\', 'MyRootClass'); // $parts = ['MyRootClass'];
$className = array_pop($parts); // $className = 'MyRootClass'; $parts = [];

if(!empty($parts)) // false

**Comment by szepeviktor** [comment]
Oh noooooooooooooooooooooooooooooooooo!
PHP is a fantastic language. `array_pop` mangles with its parameter.

Please consider using an array library.

**Comment by betterthanclay** [comment]
That's the point of using it there - taking the class name out of the array so that what is left is the namespace. 

Why use an extra dependency when array_pop does _exactly_ what is needed without any problem?

**Comment by szepeviktor** [comment]
PHP has _bad parts_.

1. changing (writing) parameteres is an anti-pattern
2. (procedural) array functions are to be read from inside out - that is also a big no-go

`Arr:create($list)->doSomething()->thenAnother()`

This is theory. In practice anything could work!

**Comment by szepeviktor** [comment]
Thinking is what I do. Viktor does not write code.
